### PR TITLE
setregion now removes the region role, then adds the new one

### LINKED ISSUE #244: Changing Region(role) Issues Welcome Again
User changed regions within the bot room and was then welcomed by the bot each time they changed (in general room).

### PR DESCRIPTION
**Pull request by ghost**
Fixes #244

### CODE REVIEW

**Review by jmariondev — COMMENTED** [review]
Was the bug that I mention in the comment fixed in discord.js? This is the approach I used when I first tried to improve this command and roles were not properly removed.

Additionally, this will not filter out people that have multiple region roles (only removes the one found as `oldRegionRole`). While an edge case, there are a handful of users that may have multiple regions set.

**Comment by ghost** [comment]
@LuaMilkshake I will look into that tomorrow if this is still open, I hadn't thought people might have several region roles. I'll try to see if there's anything different between this solution and old ones you have tried before and what those do in my test server.

**Comment by jmariondev** [comment]
Testing this PR, it looks like we're OK to do this now. I guess the bug was fixed somewhere. However, you deleted the confirmation messages that the region was changed 😉 .

Add back the
```javascript
message.reply('I\'ve set your region! :white_check_mark::map: ' +
    'Check out `!role` for other roles you can add!');
````

and some stub rejection/error handlers and we should be OK.

**Review by jmariondev — APPROVED** [review]
LGTM. I didn't test the latest commit but it worked earlier.

**Comment by jmariondev** [comment]
See #271. I would have pushed to your branch but I didn't have push access to it. soz

**Pull request closed without merging**
