### PR TITLE
New onboarding process

### PR DESCRIPTION
**Pull request by jmariondev**
This implements the new onboarding process detailed in gaymers-discord/DiscoBot#129.

Resolve gaymers-discord/DiscoBot#129.

### CODE REVIEW

**Review by brandon-a — APPROVED** [review]
Looks good to me! Thank you!

**Review by brandon-a — CHANGES_REQUESTED** [review]
Actually the welcome message should mention the new user.

**Comment by jmariondev** [comment]
The welcome message in the welcome channel? It does: https://github.com/LuaMilkshake/DiscoBot/blob/8acc6f55edba37c09b5affc0ef23ec5ce94bae95/events/memberJoined.js#L23-L24

**Review by brandon-a — APPROVED** [review]
Yeah I just noticed lol, I was viewing it in unified mode and I got a bit confused. We're all good.

**Comment by otter-computer** [comment]
A little late to add my review to this now, but looks good! Good job Mr. Milkshake ;D

**Pull request merged**
