### PR TITLE
Removes references to Member role and welcome-room

### PR DESCRIPTION
**Pull request by otter-computer**
Removes references to #welcome-room and the Member role

### CODE REVIEW

**Comment by brandon-a** [comment]
I was thinking we could keep the member role and rename it to voice chat or something like that to prevent voice chat raids that used to happen, since Mercy does not address those. But that is still up for discussion.

**Comment by Reynbow** [comment]
There's probably not much reason to change the role name. Surely changing the name of the role would require a lot more work. And who knows, we may want to use the Member role for something other than voice chat in the future.

**Review by mlarter — DISMISSED** [review]
I'm not sure how accurate this is. It's making references to a #General room yet in discord we clearly see the #welcome-Room that we are removing in this code.

**Comment by otter-computer** [comment]
@mlarter 👋 this is actually just a proposal PR for when the staff were discussing removing the #welcome-room and `Member` role. Doing that would require some bot changes, so I thought it was best to create a PR with those changes ready to go for when we were ready to remove them.

It obv didn't happen but it's still something that we might come back to, so that's why the PR has still been sitting here.

**Pull request closed without merging**
