### PR TITLE
WIP: Member Game Stats

### PR DESCRIPTION
**Pull request by chrislennon**
Please do not merge without discussion :pray:

When this goes live traffic is going to be, interesting :grin:

### CODE REVIEW

**Comment by chrislennon** [comment]
To kick off the discussion I have the following points/concerns:

- request.post should be non blocking and dismiss errors - an error from the DB or API should not result in a crash, hanging/blocking other commands etc. This should be tested on errors and long timeouts.
-  The volume of traffic may be quite obscene, the stats function will trigger any time a user comes online,offline, start/stop/change game
- The data that is captured is fairly basic and makes some assumptions (below) - we should discuss what we plan to get from this so we can capture the appropriate version of this data as early as we can

Assumptions on logging:

1. If user starts a game (previously playing nothing) - Post userid and game name.
2. If user stops playing a game (previously playing a game) - Post userid and game name + ' STOPPED'.
3. If user changes from one game to another - Post userid and previous game name + ' STOPPED' & then Post userid and new game name.

**Comment by jmariondev** [comment]
Regarding the quantity of traffic, I think it would be wise to queue these events up and only submit them to the DB when conditions are met. Maybe that's a buffer size limit or maybe just an interval (once every 10s?). I had that same thought when we were talking about architecting this.

**Comment by otter-computer** [comment]
**This PR should not be merged. It is out of date. See #174 for the latest iteration of game stats tracking.**

**Comment by otter-computer** [comment]
From some testing yesterday it appears that sending a request every presence update caused node's network stack to shit the bed after about 5 requests or so. Could have been the fact they were never closed, maybe it was that the lambda function took too long to run each time. Regardless, we decided against it 😛 

In #174 we have opted to track stats in 5 minute intervals that will grab all the games currently being played. IMO this will be more than enough data to work with rather than down to the second live stats.

**Pull request merged**
