### PR TITLE
Makes SQS an optional include

### LINKED ISSUE #245: Make SQS an optional component
Add condition at SQS queue (reading and creating) that will disable this functionality.
Provide a config overwrite so this functionality can be excluded.

### PR DESCRIPTION
**Pull request by chrislennon**
Closes #245 
I did this live without testing, while I think it would work a test or two would be appreciated.

### CODE REVIEW

**Review by jmariondev — APPROVED** [review]
Yes! Thank you for this! :smile:

**Comment by jmariondev** [comment]
I can slap it on JunkBot later if you'd like, but that'd be testing the non-SQS case :stuck_out_tongue:

**Comment by otter-computer** [comment]
I guess I'll test the other 😉

**Comment by jmariondev** [comment]
Looks like my delaying of testing this caused a bug to be merged :(

For some reason, I'm getting 'set to true' here?
```javascript
  if (appConfig.SQS_QUEUE == ''){
    appConfig.USE_AWS_SQS = false;
    console.log("set to false");
  } else {
    appConfig.USE_AWS_SQS = true;
    console.log("set to true");
  }
```

Is there an issue with changing this check to the following?
```javascript
if (!appConfig.SQS_QUEUE) {
```

**Comment by jmariondev** [comment]
Oh, it looks like @coderMess's branch needs to be rebased on master, I guess that was an old revision of this feature? Soz for the email spam 😛

**Pull request merged**
